language: csharp
mono: none
dotnet: 1.0.4
dist: trusty
branches:
  only:
   - master
install:
 - dotnet restore
script:
 - dotnet build -c Release
 - dotnet test -c Release test/unit/Chess.Test/Chess.Test.csproj
 - dotnet test -c Release test/unit/Chess.Multiplayer.Test/Chess.Multiplayer.Test.csproj
 - dotnet test -c Release test/unit/Chess.UI.Console.Test/Chess.UI.Console.Test.csproj