language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
branches:
  only:
   - master
install:
 - dotnet restore
script:
 - dotnet build -c Release
 - dotnet test -c Release test/unit/Chess.Test/Chess.Test.csproj
 - dotnet test -c Release test/unit/Chess.Multiplayer.Test/Chess.Multiplayer.Test.csproj
 - dotnet test -c Release test/unit/Chess.Terminal.Test/Chess.Terminal.Test.csproj