# Reference: https://www.appveyor.com/docs/appveyor-yml/
#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}

branches:
  only:
    - master

skip_tags: true


#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

pull_requests:
  do_not_increment_build_number: true


#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration:
  - Release

before_build:
  - dotnet restore

build_script:
  - dotnet build -c %CONFIGURATION%


#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - dotnet test -c %CONFIGURATION% test\unit\Chess.Test\Chess.Test.csproj
  - dotnet test -c %CONFIGURATION% test\unit\Chess.Multiplayer.Test\Chess.Multiplayer.Test.csproj
  - dotnet test -c %CONFIGURATION% test\unit\Chess.UI.Console.Test\Chess.UI.Console.Test.csproj